# ===================================
# CONFIGURAÇÃO ÚNICA (PRODUÇÃO)
# ===================================
server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  # --- PERFIS REMOVIDOS ---

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: zenlogoficial@gmail.com
    password: ${GM_PASS_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # --- Configurações de Banco e RabbitMQ MOVIDAS para cá ---
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: ${ORACLE_USER_KEY}
    password: ${ORACLE_PASS_KEY}

  rabbitmq:
    url: ${RABBITMQ_URL} # <-- Agora esta é a ÚNICA configuração

  ai:
    openai:
      api-key: ${GPT_PASS_KEY}
      model: gpt-3.5-turbo

api:
  security:
    token:
      secret: ${SECRET_SPRING_SECURITY}